/**
 * Proxy re-export — actual implementation lives in @readany/core/db
 * This file maintains backward compatibility for app-level imports.
 */
export {
  initDatabase,
  initLocalDatabase,
  getBooks,
  getBook,
  getDeletedBookByFileHash,
  getDeletedBookByTitle,
  insertBook,
  updateBook,
  deleteBook,
  getGroups,
  insertGroup,
  updateGroup,
  deleteGroup,
  getHighlights,
  getAllHighlights,
  getAllHighlightsWithBooks,
  getHighlightStats,
  insertHighlight,
  updateHighlight,
  deleteHighlight,
  getNotes,
  getAllNotes,
  insertNote,
  updateNote,
  deleteNote,
  getBookmarks,
  insertBookmark,
  deleteBookmark,
  getThreads,
  getThread,
  insertThread,
  updateThreadTitle,
  deleteThread,
  deleteThreadsByBookId,
  getMessages,
  insertMessage,
  getReadingSessions,
  getReadingSessionsByDateRange,
  insertReadingSession,
  updateReadingSession,
  getChunks,
  insertChunks,
  deleteChunks,
  getSkills,
  insertSkill,
  upsertSkill,
  updateSkill,
  deleteSkill,
} from "@readany/core/db/database";

export type { HighlightWithBook } from "@readany/core/db/database";
