export {
  initDatabase,
  getBooks,
  getBook,
  insertBook,
  updateBook,
  deleteBook,
  getHighlights,
  getAllHighlights,
  getAllHighlightsWithBooks,
  getHighlightStats,
  insertHighlight,
  updateHighlight,
  deleteHighlight,
  getNotes,
  getAllNotes,
  insertNote,
  updateNote,
  deleteNote,
  getBookmarks,
  insertBookmark,
  deleteBookmark,
  getThreads,
  getThread,
  insertThread,
  updateThreadTitle,
  deleteThread,
  getMessages,
  insertMessage,
  getReadingSessions,
  getReadingSessionsByDateRange,
  insertReadingSession,
  updateReadingSession,
  getChunks,
  insertChunks,
  deleteChunks,
  getSkills,
  insertSkill,
  updateSkill,
  deleteSkill,
} from "./database";

export type { HighlightWithBook } from "./database";
